# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IP_Setup_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Input_IP = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Input_IP.setGeometry(QtCore.QRect(60, 120, 311, 31))
        self.Input_IP.setObjectName("Input_IP")
        self.PortSend = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PortSend.setGeometry(QtCore.QRect(60, 240, 311, 31))
        self.PortSend.setObjectName("PortSend")
        self.PortReceive = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PortReceive.setGeometry(QtCore.QRect(60, 310, 311, 31))
        self.PortReceive.setObjectName("PortReceive")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 100, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 241, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 290, 311, 16))
        self.label_3.setObjectName("label_3")
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(190, 360, 181, 25))
        self.connect_button.setObjectName("connect_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Insira o IP:"))
        self.label_2.setText(_translate("MainWindow", "Insira a porta para envio de mensagens:"))
        self.label_3.setText(_translate("MainWindow", "Insira a porta para o recebimento de mensagens:"))
        self.connect_button.setText(_translate("MainWindow", "Connect!"))
