# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_button = QtWidgets.QPushButton(self.centralwidget)
        self.left_button.setGeometry(QtCore.QRect(50, 230, 71, 101))
        self.left_button.setStyleSheet("#left_button{\n"
"background-color: transparent;\n"
"border-image: url(:/Projeto_Embarcados/icons/left_button_normal.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;\n"
"}\n"
"#left_button:pressed\n"
"{\n"
"   border-image: url(:/Projeto_Embarcados/icons/left_button_pressed.png);\n"
"}")
        self.left_button.setText("")
        self.left_button.setObjectName("left_button")
        self.right_button = QtWidgets.QPushButton(self.centralwidget)
        self.right_button.setGeometry(QtCore.QRect(240, 270, 51, 101))
        self.right_button.setStyleSheet("#right_button{\n"
"background-color: transparent;\n"
"border-image: url(:/Projeto_Embarcados/icons/right_button_normal.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;\n"
"}\n"
"#right_button:pressed\n"
"{\n"
"   border-image: url(:/Projeto_Embarcados/icons/right_button_pressed.png);\n"
"}")
        self.right_button.setText("")
        self.right_button.setObjectName("right_button")
        self.spin = QtWidgets.QSpinBox(self.centralwidget)
        self.spin.setGeometry(QtCore.QRect(370, 150, 81, 41))
        self.spin.setStyleSheet("#spin{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    text-color: darkblue;\n"
"}")
        self.spin.setMinimum(0)
        self.spin.setMaximum(180)
        self.spin.setSingleStep(30)
        self.spin.setObjectName("spin")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 511, 111))
        self.textBrowser.setStyleSheet("#textBrowser{background-color: transparent;\n"
"text-color: white;}")
        self.textBrowser.setObjectName("textBrowser")
        self.LCD1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD1.setGeometry(QtCore.QRect(360, 310, 101, 41))
        self.LCD1.setObjectName("LCD1")
        self.LCD2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD2.setGeometry(QtCore.QRect(360, 410, 101, 41))
        self.LCD2.setObjectName("LCD2")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(190, 90, 141, 25))
        self.Start.setObjectName("Start")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 290, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 390, 71, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 25))
        self.menubar.setObjectName("menubar")
        self.menuControle_de_Motores = QtWidgets.QMenu(self.menubar)
        self.menuControle_de_Motores.setObjectName("menuControle_de_Motores")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuControle_de_Motores.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">Selecione o deslocamento, e clique na seta para enviar.</span></p></body></html>"))
        self.Start.setText(_translate("MainWindow", "Start Server!"))
        self.label.setText(_translate("MainWindow", "Posição Atual"))
        self.label_2.setText(_translate("MainWindow", "Velocidade"))
        self.menuControle_de_Motores.setTitle(_translate("MainWindow", "Controle de Motores"))
